### ISSUE TITLE
Cadastrar pedido [US18]

### ISSUE THREAD

**Issue by AlefMemTav** [mdsreq-fga-unb/2022.2-Receitalista#27]
### Descrição:
Eu como usuário gostaria de poder cadastrar pedidos na aplicação para que eu possa alocar um produto a um cliente.

### Critérios de Aceitação:
- [x] Pedido tem: Cliente, produto, data
- [x] O usuário pode adicionar somente um cliente ao pedido
- [x] O sistema deve validar todas as informações antes de cadastrar o pedido, exibindo mensagens de erro caso alguma informação esteja faltando ou inválida.
- [x] Após o cadastro de um pedido deve-se mostrar uma mensagem de sucesso.

### Conclusão:
- [x] Backend
- [x] Frontend

**Comment by lucasgcaldas** [comment]
- [ ] Backend
- [ ] Frontend

**Comment by valdersonjr** [comment]
Backend feito! Qualquer pedido de mudança só avisar.
