### ISSUE TITLE
Editar pedido [US19] - CLIENTE NÃO QUER MAIS

### ISSUE THREAD

**Issue by lucasgcaldas** [mdsreq-fga-unb/2022.2-Receitalista#38]
### Descrição:
Eu como usuário gostaria de poder editar as informações de um pedido cadastrado para poder mitigar possíveis erros durante seu cadastro.

### Critérios de Aceitação:
- [ ] A edição de pedido é: Nome, cliente, produto, descrição do pedido.
- [ ] Deve-se validar todas as informações fornecidas pelo usuário antes de salvar as alterações, exibindo mensagens de erro apropriadas caso alguma informação esteja faltando ou inválida.
- [ ] Após a edição de um pedido deve-se mostrar uma mensagem de sucesso.

### Conclusão:
- [x] Backend
- [ ] Frontend

**Comment by valdersonjr** [comment]
Backend feito! Qualquer necessidade de mudança só avisar.

exemplo:
> pode passar campos nulos

{
    "client_id": "1",
    "product_id": "1",
    "total_price": "30"
}

**Comment by AlefMemTav** [comment]
Esta história de usuário foi removida por mudança na concepção do produto por parte do cliente
