### ISSUE TITLE
Matriz de Comunicação

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2022.2-Receitalista#4]
O que é QUADRO SCRUM?! Ajustar isso.

<html>
<body>

Planejamento da Sprint | Equipe do Projeto | Semanalmente | Backlog do Sprint, Quadro Scrum
-- | -- | -- | --

</body>
</html>

**Comment by AlefMemTav** [comment]
Professor, o Quadro Scrum é um artefato do Scrum, assim como o  Backlog do Sprint. Eu não entendi o que tem que ser ajustado.
