### ISSUE TITLE
Exclusão de produto [US12]

### ISSUE THREAD

**Issue by lucasgcaldas** [mdsreq-fga-unb/2022.2-Receitalista#48]
### História de Usuário:
Eu como usuário gostaria de excluir um produto cadastrado no site caso eu não o utilize mais.

### Critérios de Aceitação:
- [x] Deve ter um produto cadastrado
- [x] Usuário logado e com conta ativa deve conseguir excluir o produto

### Conclusão:
- [x] Backend
- [x] Frontend

**Comment by AlefMemTav** [comment]
Adicionei todos os critérios de aceitação.
