### ISSUE TITLE
Excluir pedido [US20]

### ISSUE THREAD

**Issue by AlefMemTav** [mdsreq-fga-unb/2022.2-Receitalista#56]
### Descrição:
Eu como usuário gostaria de poder excluir um pedido cadastrado para não utilizá-lo mais.

### Critérios de Aceitação:
- [x]  Deve-se remover completamente o pedido selecionado, sem afetar o produto e o cliente
- [x] Após a exclusão de um produto deve-se mostrar uma mensagem de sucesso.
### Conclusão:
- [x] Backend
- [x] Frontend

**Comment by lucasgcaldas** [comment]
Backend ta feito, quando acabar a tela ai avisa para a gente integrar.
