### ISSUE TITLE
Editar cliente [US15] 

### ISSUE THREAD

**Issue by AlefMemTav** [mdsreq-fga-unb/2022.2-Receitalista#57]
### Descrição:
Eu como usuário gostaria de editar as informações de um cliente para corrigir erros ou atualizá-las.

### Critérios de aceitação:
- [x] A edição de cliente é: Nome, telefone.
- [x] Deve-se validar todas as informações fornecidas pelo usuário antes de salvar as alterações, exibindo mensagens de erro apropriadas caso alguma informação esteja faltando ou inválida.
- [x] Após a edição de um cliente deve-se mostrar uma mensagem de sucesso.

### Conclusão:
- [x] Backend
- [x] Frontend

**Comment by lucasgcaldas** [comment]
backend feito, quando finalizar a tela avisa para fazer a integração
