### ISSUE TITLE
Excluir cliente [US16] 

### ISSUE THREAD

**Issue by AlefMemTav** [mdsreq-fga-unb/2022.2-Receitalista#58]
### História de Usuário:
Eu como usuário gostaria de excluir as informações de um cliente cadastrado para não utilizá-lo mais.

### Critérios de Aceitação:
- [x] Deve-se remover completamente o cliente selecionado
- [x] Após a exclusão de um cliente deve-se mostrar uma mensagem de sucesso

### Conclusão:
- [x] Backend
- [x] Frontend

**Comment by lucasgcaldas** [comment]
backend feito, quando acabar a tela avisa para a gente fazer a conexão.
