### ISSUE TITLE
Visualizar clientes [US17] 

### ISSUE THREAD

**Issue by AlefMemTav** [mdsreq-fga-unb/2022.2-Receitalista#59]
### Descrição:
Eu como usuário gostaria de visualizar a listagem dos meus clientes cadastrados para gerenciar seus pedidos.

### Critérios de aceitação:
- [x] A visualização do cliente é: nome, telefone.
- [x] Para cada produto deve ser visível as opções de editar e excluir.

### Conclusão:
- [x] Backend
- [x] Frontend

**Comment by lucasgcaldas** [comment]
backend feito, quando acabar a tela avisa para conectar com o front
